const THEME = {
  "appTitle": "簿記3級 仕訳演習ドリル",
  "appLogo": "📘",
  "submitBtnText": "仕訳を判定する",
  "storagePrefix": "boki_template",
  "fontUrl": "",
  "fontTitle": "-apple-system, BlinkMacSystemFont, 'Hiragino Kaku Gothic ProN', 'Yu Gothic', sans-serif",
  "fontMain": "-apple-system, BlinkMacSystemFont, 'Hiragino Kaku Gothic ProN', 'Yu Gothic', sans-serif",
  "cardWatermark": "PRACTICE DRILL // STAGE-01",
  "watermarkColor": "#94a3b8",
  "risingSymbols": ["✨", "⭕", "🎉", "🌟"],
  "colors": {
    "--primary": "#2563eb",
    "--primary-hover": "#1d4ed8",
    "--bg-body": "#f8fafc",
    "--bg-gradient": "radial-gradient(circle at 50% 10%, #ffffff 0%, #f1f5f9 100%)",
    "--card-bg": "#ffffff",
    "--card-text": "#0f172a",
    "--card-shadow": "0 2px 8px rgba(0, 0, 0, 0.04), inset 0 0 0 1px rgba(0,0,0,0.02)",
    "--container-glow": "0 8px 24px rgba(0, 0, 0, 0.06)",
    "--text-main": "#0f172a",
    "--text-muted": "#64748b",
    "--border": "#cbd5e1",
    "--debit-border": "#3b82f6",
    "--credit-border": "#ef4444",
    "--correct-bg": "#dcfce7",
    "--correct-text": "#166534",
    "--wrong-bg": "#fee2e2",
    "--wrong-text": "#991b1b"
  }
};
